---
title: "Senior Project"
author: "Emily Johnson"
date: "3/13/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

## Data 


```{r}
data <- read.csv("/Users/emilyjohnson/Desktop/Stats_Senior_Project_Data.csv", header = TRUE)
data_sub <- data[c(1:3,19)]
data_sub <- data.frame(data_sub)
data_sub <- na.omit(data_sub)
data_sub <- data_sub[-109,]
data_study1 <- subset(data_sub, studyid < 700)
data_study2 <- subset(data_sub, studyid > 700)

for(i in 1:nrow(data_sub)){
  
  if((data_sub$VISIT[i] == 1 & data_sub$bottype[i] == 1) | 
     (data_sub$VISIT[i] == 2 & data_sub$bottype[i] == 2)){
    data_sub$type[i] <- 'A'
  } else {
    data_sub$type[i] <- 'B'
  }
  
}


```


## Group A Data
```{r}
groupA <- subset(data_sub, type == 'A')
groupA_clear <- subset(groupA, bottype == 1)
groupA_opaque <- subset(groupA, bottype == 2)
groupA <- cbind(groupA_clear, groupA_opaque$tfamtml)
groupA <- subset(groupA[,c(1,4,6)])
names(groupA) <- c("Study ID", "Clear Bottle mL", "Opaque Bottle mL")
groupA$Difference <- groupA$`Clear Bottle mL` - groupA$`Opaque Bottle mL`
groupASummary <- cbind(rbind(mean(groupA$`Clear Bottle mL`),sd(groupA$`Clear Bottle mL`)),rbind(mean(groupA$`Opaque Bottle mL`), sd(groupA$`Opaque Bottle mL`)),rbind(mean(groupA$Difference),sd(groupA$Difference)))
rownames(groupASummary) <- c("Mean", "Std. Dev")
colnames(groupASummary) <- c("Clear Bottle", "Opaque Bottle", "Difference")
groupASummary
plot(groupA$`Clear Bottle mL`, groupA$`Opaque Bottle mL`, 
     xlab = "Clear Bottle mL", ylab = "Opaque Bottle mL", main = "Group A", pch = 20)
abline(lm(groupA$`Clear Bottle mL`~groupA$`Opaque Bottle mL`), col = "red")
cor(groupA$`Clear Bottle mL`, groupA$`Opaque Bottle mL`)

t.test(groupA$`Clear Bottle mL`, groupA$`Opaque Bottle mL`, paired = TRUE)

```

## Group B Data
```{r}
groupB <- subset(data_sub, type == 'B')
groupB_clear <- subset(groupB, bottype == 1)
groupB_opaque <- subset(groupB, bottype == 2)
groupB <- cbind(groupB_clear, groupB_opaque$tfamtml)
groupB <- subset(groupB[,c(1,4,6)])
names(groupB) <- c("Study ID", "Clear Bottle mL", "Opaque Bottle mL")
groupB$Difference <- groupB$`Clear Bottle mL` - groupB$`Opaque Bottle mL`
groupBSummary <- cbind(rbind(mean(groupB$`Clear Bottle mL`),sd(groupB$`Clear Bottle mL`)),rbind(mean(groupB$`Opaque Bottle mL`), sd(groupB$`Opaque Bottle mL`)),rbind(mean(groupB$Difference),sd(groupB$Difference)))
rownames(groupBSummary) <- c("Mean", "Std. Dev")
colnames(groupBSummary) <- c("Clear Bottle", "Opaque Bottle", "Difference")
groupBSummary
plot(groupB$`Clear Bottle mL`, groupB$`Opaque Bottle mL`, 
     xlab = "Clear Bottle mL", ylab = "Opaque Bottle mL", main = "Group B", pch = 20)
abline(lm(groupB$`Clear Bottle mL`~groupB$`Opaque Bottle mL`), col = "red")
cor(groupB$`Clear Bottle mL`, groupB$`Opaque Bottle mL`)

t.test(groupB$`Clear Bottle mL`, groupB$`Opaque Bottle mL`, paired = TRUE)

```

## Power Group A

```{r}
powers <- seq(from = .7, to = .9, by = .02)
samplesizes <- rep(NA,length(powers))
for(i in 1:length(powers))
{
  power <- power.t.test(delta = mean(groupA$Difference), sd = sd(groupA$Difference), power = powers[i], type = "one.sample")
  samplesizes[i] <- power$n  
}
power_matrixA <- cbind(powers, samplesizes)
power_matrixA
```

## Power Simulation

```{r}
n <- 305
mu <- 8.879838
sigma <- 47.65847
mu0 <- 0
reps <- 10000
outsideCI <- numeric(reps)
set.seed(2)
for (i in 1:reps) {
  x <- rnorm(n, mu, sigma)
  CI.lower <- mean(x) - qt(0.975, n-1)*sd(x)/sqrt(n)
  CI.upper <- mean(x) + qt(0.975, n-1)*sd(x)/sqrt(n)
  outsideCI[i] <- ifelse(mu0 < CI.lower | mu0 > CI.upper, 1, 0)
}
mean(outsideCI)
```

## Power Group B

```{r}
powers <- seq(from = .7, to = .9, by = .02)
samplesizes <- rep(NA,length(powers))
for(i in 1:length(powers))
{
  power <- power.t.test(delta = mean(groupB$Difference), sd = sd(groupB$Difference), power = powers[i], 
                        type = "one.sample")
  samplesizes[i] <- power$n  
}
power_matrixB <- cbind(powers, samplesizes)
power_matrixB

```

## Power Simulation

```{r}
n <- 456
mu <- 6.974264
sigma <- 45.84868
mu0 <- 0
reps <- 10000
outsideCI <- numeric(reps)
set.seed(2)
for (i in 1:reps) {
  x <- rnorm(n, mu, sigma)
  CI.lower <- mean(x) - qt(0.975, n-1)*sd(x)/sqrt(n)
  CI.upper <- mean(x) + qt(0.975, n-1)*sd(x)/sqrt(n)
  outsideCI[i] <- ifelse(mu0 < CI.lower | mu0 > CI.upper, 1, 0)
}
mean(outsideCI)
```

## Power Function

```{r}
power_func <- function(r, n, s1, s2, delta)
{
  sd_diff <- sqrt(s1^2 + s2^2 - 2*r*s1*s2)
  power <- power.t.test(n, delta = delta, sd = sd_diff, type = "paired")
  return(power$power)
}

r <- seq(0.1,0.9,by=0.05)
n <- c(35,40,45)
delta <- c(5, 10, 15, 20)
s1 <- c(35, 40, 45, 50)
k = length(r)*length(n)*length(s1)
power_df1 <- data.frame(n = rep(NA,k), r = rep(NA,k), s1 = rep(NA,k), power = rep(NA,k))
index <- 0
for(i in 1:length(n)) {
  for(j in 1:length(r)) {
    for(m in 1:length(s1)) {
      index <- index + 1
      power_df1[index,1] <- n[i]
      power_df1[index,2] <- r[j]
      power_df1[index,3] <- s1[m]
      power_df1[index,4] <- power_func(r[j], n[i], s1[m], 
                                      .75*s1[m], delta[2])
      }
    } 
  }
sd_vals <- list("SD = 35", "SD = 40", "SD = 45", "SD = 50")
ggplot(power_df1, aes(x = r, y = power, col = as.factor(n))) + geom_line() + facet_wrap( ~ s1, ncol = 2, labeller = label_both) + xlab("Correlation") + ylab("Power")  + labs(col = "Sample Size")


power_df2 <- data.frame(n = rep(NA,k), r = rep(NA,k), delta = rep(NA,k), power = rep(NA,k))
index <- 0
for(i in 1:length(n)) {
  for(j in 1:length(r)) {
    for(m in 1:length(delta)) {
      index <- index + 1
      power_df2[index,1] <- n[i]
      power_df2[index,2] <- r[j]
      power_df2[index,3] <- delta[m]
      power_df2[index,4] <- power_func(r[j], n[i], s1[1], 
                                      s1[2], delta[m])
      }
    } 
  }
delta_vals <- list("delta = 5", "delta = 10", "delta = 15", "delta = 20")
ggplot(power_df2, aes(x = r, y = power, col = as.factor(n))) + geom_line() + facet_wrap( ~ delta, ncol = 2, labeller = label_both) + xlab("Correlation") + ylab("Power")  + labs(col = "Sample Size")
```
